# Generated by Django 4.0.6 on 2022-07-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('truck_type', models.CharField(choices=[('pick_up', 'Pick up truck'), ('van', 'Van'), ('small', 'Small moving truck'), ('medium', 'Medium moving truck'), ('large', 'Large moving truck')], max_length=30)),
            ],
        ),
    ]
